DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS secured_app;
DROP TABLE IF EXISTS app_group;
DROP TABLE IF EXISTS user_group_app;

CREATE TABLE app_group (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_name VARCHAR(255) NOT NULL UNIQUE,
  secured_app_id INT NOT NULL,
  created_by VARCHAR(255) NOT NULL
);

CREATE TABLE user_group_app (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  created_by VARCHAR(255) NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  token VARCHAR(255) UNIQUE
);

CREATE TABLE secured_app (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  app_name VARCHAR(255) NOT NULL UNIQUE,
  created_by VARCHAR(255) NOT NULL
);
